package com.zpi.bmarket.bmarket;

public enum PostStatus {
    SUCCESS,
    ERROR,
    DATABASE_ERROR,
    WRONG_PASSWORD,
    WRONG_USERNAME,
    WRONG_PASSWORD_OR_USERNAME,
    WEAK_PASSWORD,
    EMAIL_NOT_VALID,
    LOGIN_DUPLICATE,
    EMAIL_DUPLICATE,
    PASSWORDS_NOT_MATCH
}
